---
- name: Pocket knife for ansible-bender
  hosts: all
  tasks:
  - name: Install all packages needed to hack on ab.
    dnf:
      name:
      - python3-pip
      - python3-setuptools
      - git
      - python3-setuptools_scm
      - python3-setuptools_scm_git_archive
      - python3-wheel  # for bdist_wheel
      - git
      - containers-common
      - buildah
      - podman
      - ansible
  - name: Install latest twine for sake of check command
    pip:
      name:
      - twine  # we need newest twine, b/c of the check command
      - readme_renderer[md]
      state: latest
  - name: stat /src
    stat:
      path: /src
    tags:
    - no-cache
    register: src_path
  - name: Let's make sure /src is present
    assert:
      that:
      - 'src_path.stat.isdir'
  # this requires to have sources mounted inside at /src
  - name: Install source-git from the current working directory
    pip:
      name: /src
  - name: Change storage driver to vfs (ovl on ovl doesn't work)
    lineinfile:
      path: /etc/containers/storage.conf
      regexp: '^driver = '
      line: 'driver = "vfs"'
  - name: Change storage driver graphroot to /tmp/containers
    lineinfile:
      path: /etc/containers/storage.conf
      regexp: '^graphroot = '
      line: 'graphroot = "/tmp/containers"'
  - name: copy libpod.conf
    copy:
      src: /usr/share/containers/libpod.conf
      dest: /etc/containers/libpod.conf
  - name: Change cgroup driver to cgroupfs.
    lineinfile:
      path: /etc/containers/libpod.conf
      regexp: '^cgroup_manager = '
      line: 'cgroup_manager = "cgroupfs"'

